### ISSUE TITLE
Home & Action Menu Screens Design implementation

### ISSUE THREAD

**Issue by alaazamelDev** [alaazamelDev/gofit#7]
### Through out this issue we have the following tasks

- [x] Add navigation bar for main screen
- [x] Create main screen structure with related pages

### After setting up the main hierarchy for main screen we need to 

- [x] implement home page design
- [x] implement workout levels screen
- [x] implement notifications screen 
- [x] implement bookmarks screen
- [x] implement bookmark removal design

### Presentation

<table align="center">

  
  <tr align="center">
    <td>
      <h3>Home Page</h3>
    </td>
    <td>
      <h3>Workout Levels</h3>
    </td>
    <td>
      <h3>Notifications</h3>
    </td>
  </tr>

  
  <tr>
    <td><img src="https://raw.githubusercontent.com/alaazamelDev/gofit/master/design/27_Light_home%20fit%20page.png" alt=""></td>
    <td> <img src="https://raw.githubusercontent.com/alaazamelDev/gofit/master/design/28_Light_home%20workout%20levels.png" alt=""></td>
    <td>
      <img src="https://raw.githubusercontent.com/alaazamelDev/gofit/master/design/29_Light_home%20notification.png">
    </td>
  </tr>
  
   
  <tr align="center">
    <td>
      <h3>Bookmarks</h3>
    </td>
    <td>
      <h3>Bookmark Removal</h3>
    </td>
  </tr>

  
  <tr>
    <td><img src="https://raw.githubusercontent.com/alaazamelDev/gofit/master/design/30_Light_home%20my%20bookmark.png" alt=""></td>
    <td> <img src="https://raw.githubusercontent.com/alaazamelDev/gofit/master/design/31_Light_home%20my%20bookmark%20remove%20modal.png" alt=""></td>
  </tr>
</table>

**Comment by SwaroopSambhayya** [comment]
Hi can i contribute to Workout levels screen?

**Comment by alaazamelDev** [comment]
Yes Of Course,  and follow the same folder structure organization

**Comment by alaazamelDev** [comment]
@SwaroopSambhayya Are you working on Workout Levels or Not?

**Comment by alaazamelDev** [comment]
### UPDATE 🗓 

- #### Home Page Design implementation Completed ✅✅

**Comment by SwaroopSambhayya** [comment]
Yep Im working on it, it will be completed by today

**Comment by alaazamelDev** [comment]
### UPDATE 🗓

- ##### Implementing my bookmarks screen design is Completed ✅✅

### NEXT 

- ##### Bookmark removal design

**Comment by alaazamelDev** [comment]
### UPDATE 🗓

- ##### Implementing bookmark removal Design is Completed ✅✅

### NEXT
- ##### Implementing Notifications screen design

**Comment by alaazamelDev** [comment]
### UPDATE 🗓

- ##### Implementing Notifications screen is completed ✅✅

**Comment by SwaroopSambhayya** [comment]
Hi @alaazamelDev  I have raises PR for workout level design #8
